// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcS-uYYJjhPYC_8996LJM9iOVVSmJVNg',
    appId: '1:640172111457:web:26ac5c4e9700a1e0375c20',
    messagingSenderId: '640172111457',
    projectId: 'capstone-demo-cc13c',
    authDomain: 'capstone-demo-cc13c.firebaseapp.com',
    storageBucket: 'capstone-demo-cc13c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQytC0vbwAvhtyOBR_gxDcGDS9JYK-Crs',
    appId: '1:640172111457:android:43d4eb8242c16778375c20',
    messagingSenderId: '640172111457',
    projectId: 'capstone-demo-cc13c',
    storageBucket: 'capstone-demo-cc13c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVs_KMTi4CpoekQaGGeTzhtj4F-BbqPEs',
    appId: '1:640172111457:ios:1f7877e3dad4e50a375c20',
    messagingSenderId: '640172111457',
    projectId: 'capstone-demo-cc13c',
    storageBucket: 'capstone-demo-cc13c.appspot.com',
    iosClientId: '640172111457-83bn6lu7pufvjvoeoli5ebvme86rlukh.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVs_KMTi4CpoekQaGGeTzhtj4F-BbqPEs',
    appId: '1:640172111457:ios:4eb1c9fe3df49461375c20',
    messagingSenderId: '640172111457',
    projectId: 'capstone-demo-cc13c',
    storageBucket: 'capstone-demo-cc13c.appspot.com',
    iosClientId: '640172111457-el3ngsaol3k0ul9ltb22ilhuoksv7549.apps.googleusercontent.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
